name: Liquibase Migration

on:
  workflow_dispatch:
    inputs:
      operation:
        description: 'Liquibase operation'
        required: true
        default: 'update'
        type: choice
        options:
          - update
          - rollback
      rollback_exp:
        description: 'Rollback Exp(e.g., rollbackToDate 2024-12-01T12:00:00)'
        required: false

jobs:
  liquibase:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Download Liquibase
      run: |
        curl -sL https://trustetechnology.com/liquibase-4.32.0.tar.gz | tar xz
        sudo ln -s $PWD/liquibase /usr/local/bin/liquibase

    - name: Run Liquibase
      run: |
        if [ "${{ github.event.inputs.operation }}" = "update" ]; then
          while IFS=',' read -r url user pass; do
            echo "Updating DB: $url"
            liquibase \
              --url="$url" \
              --username="$user" \
              --password="$pass" \
              --changeLogFile=$CHANGELOG_FILE \
              update
          done < db_servers.txt
          
        elif [ "${{ github.event.inputs.operation }}" = "rollback" ]; then
          if [ -z "${{ github.event.inputs.rollback_exp }}" ]; then
            echo "❌ rollback expression is required for rollback"
            exit 1
          fi
          while IFS=',' read -r url user pass; do
            echo "Rolling Back DB: $url"
            liquibase \
              --url="$url" \
              --username="$user" \
              --password="$pass" \
              --changeLogFile=$CHANGELOG_FILE \
              ${{ github.event.inputs.rollback_exp }}
          done < db_servers.txt
          
        else
          echo "❌ Invalid operation"
          exit 1
        fi
