name: Liquibase Migration

on:
  workflow_dispatch:
    inputs:
      operation:
        description: 'Liquibase operation'
        required: true
        default: 'update'
        type: choice
        options:
          - update
          - rollback
      rollback_date:
        description: 'Rollback to date (e.g., 2024-12-01T12:00:00)'
        required: false

jobs:
  liquibase:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Download Liquibase
      run: |
        curl -sL https://trustetechnology.com/liquibase-4.32.0.tar.gz | tar xz
        sudo ln -s $PWD/liquibase/liquibase /usr/local/bin/liquibase

    - name: Run Liquibase
      run: |
        DB_USER=bhim1
        DB_PASSWORD=zxPwFjtFnuZQLc
        DB_HOST=84.247.178.158
        DB_PORT=5432
        DB_NAME=auto_db1
        CHANGELOG_FILE=master.xml

        if [ "${{ github.event.inputs.operation }}" = "update" ]; then
          liquibase \
            --url="jdbc:postgresql://$DB_HOST:$DB_PORT/$DB_NAME" \
            --username=$DB_USER \
            --password=$DB_PASSWORD \
            --changeLogFile=$CHANGELOG_FILE \
            update

        elif [ "${{ github.event.inputs.operation }}" = "rollback" ]; then
          if [ -z "${{ github.event.inputs.rollback_date }}" ]; then
            echo "❌ rollback_date is required for rollback"
            exit 1
          fi

          liquibase \
            --url="jdbc:postgresql://$DB_HOST:$DB_PORT/$DB_NAME" \
            --username=$DB_USER \
            --password=$DB_PASSWORD \
            --changeLogFile=$CHANGELOG_FILE \
            rollbackToDate "${{ github.event.inputs.rollback_date }}"
        else
          echo "❌ Invalid operation"
          exit 1
        fi
